### ISSUE TITLE
Add builders residency page

### ISSUE THREAD

**Issue by closerearth** [closerdao/closer-ui#554]
We would like to add a new type of booking application to TDF website which can mimic to a certain extent volunteering - but the goal is to have a sexy builder residency landing page we can drive builders to.

Content:
- Video (explaining TDF, the residency concept, and projects needed on the ground)
- https://docs.google.com/document/d/1QXvgGriPOKljBpQEdE68ApLL6pPkeAxs4u5sIdyY0sE/edit Copy
- Booking form > Similar to volunteering but with added: what are your skills (electricity, plumbing, woodwork... > should fill out the users profile), what project could you support with)

<img width="308" alt="Screenshot 2024-10-08 at 11 14 19" src="https://github.com/user-attachments/assets/3abb0332-2600-495d-a9a0-076c9663220a">

**Comment by francaye** [comment]
Here is the Figma file with the designs: https://www.figma.com/design/Oy8ESFpUDdcFZYd6bsk6gc?node-id=4352-12603#1000073930 @valieff

**Comment by valieff** [comment]
- I think skills & qualifications can move into a simple backend config (editable tag list for example)
- However we have this new "Projects" category which could replace our current "Volunteer" object, with a few added fields:
/project Project 

```
{
 name: 'BioPool', 
 description: 'We are building a 15x4m natural pool.', 
 skills: ['cement', 'water plants', 'geomembrane'], 
 reward: {val: 4, cur: '$TDF'}, 
document: 'url of working document (usually google Doc)',
estimate: '4 days', // days of work
 managedBy: ['UserID that picked this project (already in base _model)'], // in the list of Projects - Space Host role should be able to assign a user to a project by searching from the user list
 start: '2024-01-01', 
 end: '2025-01-01'
}
```

Added this comment to the design of the residency page that we add previews of the projects:
Each project can have the following fields:
Budget: EUR needed for materials etc
Reward: $TDF or EUR reward for completing the project
Estimate: how many days to complete
Link: link to a document describing the project details - i.e. biopooL: https://docs.google.com/document/d/1yDdABZ1MLl5SfTr8QyK7OML6Nk_bzr2KY0OxUjrm9nU/edit
Start & end dates (optional)
ManagedBy: The User (resident) who is in charge of the project
Skills required: list of skills (carpentry, masonry etc)


UI Changes:
- We are transforming the concept of volunteering opportunities into build projects (backend Volunteer object becomes Project)
- Residents can "own" a project (by being assigned project.managedBy = userID)
- Projects that have managedBy = null are available to be picked up for a residency
- Add new /projects page - copy paste of the current /volunteer page listing the projects. Display projects in a grid with a preview of each project. Project detail page (/volunteer/ID) can remain as is. If user clicks "apply" from there we should take them to /residency/apply?project=ID and pre-fill the project field.
- Simplify /volunteer page as per the flow in the figma. Booking with volunteering: instead of having a volunteeringID we should just have a isVolunteer flag instead since volunteer does not require to have a project associated.
- Add the /residency page as designed (+ the list of projects component that needs to be added). Skills & qualifications can be rendered from a config list.
